version: 2.1
orbs:
  node: circleci/node@5.0.2
  docker: circleci/docker@1.5.0

executors:
  docker-publisher: 
            environment:
            docker:
              - image: circleci/node:latest
                auth:
                  username: $DOCKERHUB_USER
                  password: $DOCKERHUB_PASS

jobs:
  Build: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      
      - run:
          command:   CI=false yarn build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths: .

  publish-docker-image:
    executor: docker-publisher
    steps:
         - checkout
         - setup_remote_docker
         - run:
            name: Publish docker image to docker hub
            command : |
             echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
             docker build . -t teamrulerhng9/frontend:latest
             docker push teamrulerhng9/frontend:latest

  Deploy-staging:
     machine:
        enabled: true
     steps:
        - run:
            name: Deploy Over SSH
            command : |
             ssh $SSH_USER@$SSH_HOST "cd todoassistant.api" || "docker-compose down" || "docker-compose up -d" 
workflows:
  front-workflow: 
      jobs: 
         - Build
         - publish-docker-image:
                 requires:
                   - Build

                 filters: 
                     branches:
                       only: 
                         - Development
                         

         - Deploy-staging:
                requires: 
                    - Build
                    - publish-docker-image
                filters:
                      branches:
                        only:
                          - Development
                          
                          

   
